#!/usr/bin/env python3
"""
Team Registry for Premium Project Generator V2.
Manages a shared catalog of Windsurf tools (Rules, Skills, Workflows)
for team-wide distribution and discovery.

Usage:
    python3 team-registry.py init --name "Acme Corp Tools"
    python3 team-registry.py publish <path_to_kit> --tags tag1,tag2
    python3 team-registry.py list
    python3 team-registry.py search "query"
    python3 team-registry.py install <tool-name>
    python3 team-registry.py stale
    python3 team-registry.py info <tool-name>
    python3 team-registry.py remove <tool-name>

Exit codes:
    0 = Success
    1 = Error
"""

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


DEFAULT_REGISTRY_DIR = os.path.expanduser("~/windsurf-tools-registry")
REGISTRY_FILE = "registry.json"
TOOLS_DIR = "tools"


def init_registry(registry_dir: str, name: str) -> dict:
    """Initialise a new team registry."""
    root = Path(registry_dir)
    root.mkdir(parents=True, exist_ok=True)
    (root / TOOLS_DIR).mkdir(exist_ok=True)

    registry = {
        "name": name,
        "version": "1.0.0",
        "created": datetime.now().isoformat(),
        "updated": datetime.now().isoformat(),
        "tools": [],
        "metadata": {
            "generator": "premium-project-generator-v2",
            "total_tools": 0,
        },
    }

    registry_path = root / REGISTRY_FILE
    registry_path.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")

    # Generate README
    readme = root / "README.md"
    readme.write_text(
        f"# {name}\n\n"
        f"Team Windsurf Tools Registry — generated by Premium Project Generator V2.\n\n"
        f"## Quick Start\n\n"
        f"```bash\n"
        f"# Clone the registry\n"
        f"git clone <repo-url> {registry_dir}\n\n"
        f"# List available tools\n"
        f"python3 team-registry.py list --registry {registry_dir}\n\n"
        f"# Search for a tool\n"
        f"python3 team-registry.py search \"keyword\" --registry {registry_dir}\n\n"
        f"# Install a tool\n"
        f"python3 team-registry.py install tool-name --registry {registry_dir}\n"
        f"```\n",
        encoding="utf-8",
    )

    print(f"Registry initialised at {registry_dir}")
    print(f"Name: {name}")
    return registry


def load_registry(registry_dir: str) -> dict:
    """Load an existing registry."""
    registry_path = Path(registry_dir) / REGISTRY_FILE
    if not registry_path.exists():
        print(f"Error: No registry found at {registry_dir}. Run 'init' first.", file=sys.stderr)
        sys.exit(1)
    return json.loads(registry_path.read_text(encoding="utf-8"))


def save_registry(registry_dir: str, registry: dict) -> None:
    """Save the registry to disk."""
    registry["updated"] = datetime.now().isoformat()
    registry["metadata"]["total_tools"] = len(registry["tools"])
    registry_path = Path(registry_dir) / REGISTRY_FILE
    registry_path.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")


def publish_tool(registry_dir: str, tool_path: str, tags: list[str]) -> dict:
    """Publish a Windsurf tool kit to the registry."""
    registry = load_registry(registry_dir)
    root = Path(tool_path)

    if not root.is_dir():
        print(f"Error: {tool_path} is not a valid directory", file=sys.stderr)
        sys.exit(1)

    # Detect tool type and name
    tool_name = root.name
    tool_type = "kit"  # default

    skill_md = root / "SKILL.md"
    agents_md = root / "AGENTS.md"

    version = "1.0.0"
    description = ""

    if skill_md.exists():
        tool_type = "skill"
        content = skill_md.read_text(encoding="utf-8", errors="replace")
        match = re.search(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
        if match:
            for line in match.group(1).split("\n"):
                kv = re.match(r"^version\s*:\s*(.+)$", line.strip())
                if kv:
                    version = kv.group(1).strip().strip("'\"")
                kv = re.match(r"^name\s*:\s*(.+)$", line.strip())
                if kv:
                    tool_name = kv.group(1).strip().strip("'\"")
    elif agents_md.exists():
        tool_type = "agents"

    # Count files
    file_count = sum(1 for _ in root.rglob("*") if _.is_file())

    # Check for duplicates
    existing = [t for t in registry["tools"] if t["name"] == tool_name]
    if existing:
        # Update existing entry
        entry = existing[0]
        entry["version"] = version
        entry["updated"] = datetime.now().isoformat()
        entry["tags"] = tags
        entry["file_count"] = file_count
        action = "updated"
    else:
        entry = {
            "name": tool_name,
            "type": tool_type,
            "version": version,
            "description": description,
            "tags": tags,
            "published": datetime.now().isoformat(),
            "updated": datetime.now().isoformat(),
            "author": os.environ.get("USER", os.environ.get("USERNAME", "unknown")),
            "file_count": file_count,
            "path": f"{TOOLS_DIR}/{tool_name}",
        }
        registry["tools"].append(entry)
        action = "published"

    # Copy tool to registry
    dest = Path(registry_dir) / TOOLS_DIR / tool_name
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(root, dest)

    save_registry(registry_dir, registry)

    print(f"Tool '{tool_name}' {action} to registry.")
    print(f"  Type:    {tool_type}")
    print(f"  Version: {version}")
    print(f"  Tags:    {', '.join(tags)}")
    print(f"  Files:   {file_count}")

    return entry


def list_tools(registry_dir: str, json_output: bool = False) -> None:
    """List all tools in the registry."""
    registry = load_registry(registry_dir)

    if json_output:
        print(json.dumps(registry["tools"], indent=2, ensure_ascii=False))
        return

    print(f"\n  {registry['name']} — {len(registry['tools'])} tools\n")
    if not registry["tools"]:
        print("  (empty registry)")
        return

    print(f"  {'NAME':<25} {'TYPE':<10} {'VERSION':<10} {'TAGS':<30} {'UPDATED':<12}")
    print(f"  {'-'*25} {'-'*10} {'-'*10} {'-'*30} {'-'*12}")

    for tool in registry["tools"]:
        tags = ", ".join(tool.get("tags", []))[:28]
        updated = tool.get("updated", "")[:10]
        print(f"  {tool['name']:<25} {tool['type']:<10} {tool['version']:<10} {tags:<30} {updated}")


def search_tools(registry_dir: str, query: str, json_output: bool = False) -> None:
    """Search tools by name, tags, or description."""
    registry = load_registry(registry_dir)
    q = query.lower()

    results = []
    for tool in registry["tools"]:
        searchable = f"{tool['name']} {' '.join(tool.get('tags', []))} {tool.get('description', '')}".lower()
        if q in searchable:
            results.append(tool)

    if json_output:
        print(json.dumps(results, indent=2, ensure_ascii=False))
        return

    print(f"\n  Search: '{query}' — {len(results)} results\n")
    for tool in results:
        tags = ", ".join(tool.get("tags", []))
        print(f"  {tool['name']} (v{tool['version']}) — [{tags}]")


def install_tool(registry_dir: str, tool_name: str, target_dir: Optional[str] = None) -> None:
    """Install a tool from the registry to the local workspace."""
    registry = load_registry(registry_dir)
    tool = next((t for t in registry["tools"] if t["name"] == tool_name), None)

    if not tool:
        print(f"Error: Tool '{tool_name}' not found in registry.", file=sys.stderr)
        sys.exit(1)

    source = Path(registry_dir) / tool["path"]
    if not source.exists():
        print(f"Error: Tool files not found at {source}", file=sys.stderr)
        sys.exit(1)

    # Auto-detect install location
    if target_dir is None:
        if tool["type"] == "skill":
            target_dir = f".devin/skills/{tool_name}"
        elif tool["type"] == "agents":
            target_dir = "."
        else:
            target_dir = f".devin/tools/{tool_name}"

    dest = Path(target_dir)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(source, dest)

    print(f"Installed '{tool_name}' → {target_dir}")
    print(f"  Type:    {tool['type']}")
    print(f"  Version: {tool['version']}")


def tool_info(registry_dir: str, tool_name: str) -> None:
    """Show detailed information about a tool."""
    registry = load_registry(registry_dir)
    tool = next((t for t in registry["tools"] if t["name"] == tool_name), None)

    if not tool:
        print(f"Error: Tool '{tool_name}' not found.", file=sys.stderr)
        sys.exit(1)

    print(json.dumps(tool, indent=2, ensure_ascii=False))


def remove_tool(registry_dir: str, tool_name: str) -> None:
    """Remove a tool from the registry."""
    registry = load_registry(registry_dir)
    original_count = len(registry["tools"])
    registry["tools"] = [t for t in registry["tools"] if t["name"] != tool_name]

    if len(registry["tools"]) == original_count:
        print(f"Error: Tool '{tool_name}' not found.", file=sys.stderr)
        sys.exit(1)

    # Remove files
    tool_dir = Path(registry_dir) / TOOLS_DIR / tool_name
    if tool_dir.exists():
        shutil.rmtree(tool_dir)

    save_registry(registry_dir, registry)
    print(f"Removed '{tool_name}' from registry.")


def check_stale(registry_dir: str, json_output: bool = False) -> None:
    """Check staleness of all tools in the registry."""
    registry = load_registry(registry_dir)
    now = datetime.now()

    results = []
    for tool in registry["tools"]:
        updated_str = tool.get("updated", tool.get("published", ""))
        try:
            updated = datetime.fromisoformat(updated_str)
        except ValueError:
            updated = now

        days_since = (now - updated).days
        if days_since > 180:
            status = "CRITICAL"
        elif days_since > 90:
            status = "STALE"
        elif days_since > 60:
            status = "AGING"
        else:
            status = "FRESH"

        results.append({
            "name": tool["name"],
            "version": tool["version"],
            "status": status,
            "days_since_update": days_since,
            "last_updated": updated_str[:10],
        })

    if json_output:
        print(json.dumps(results, indent=2, ensure_ascii=False))
        return

    print(f"\n  Staleness Report — {registry['name']}\n")
    print(f"  {'NAME':<25} {'VERSION':<10} {'STATUS':<10} {'DAYS':<6} {'UPDATED':<12}")
    print(f"  {'-'*25} {'-'*10} {'-'*10} {'-'*6} {'-'*12}")

    for r in results:
        icon = {"FRESH": "🟢", "AGING": "🟡", "STALE": "🟠", "CRITICAL": "🔴"}.get(r["status"], "⚪")
        print(f"  {icon} {r['name']:<23} {r['version']:<10} {r['status']:<10} {r['days_since_update']:<6} {r['last_updated']}")


def main():
    parser = argparse.ArgumentParser(description="Team Registry for PPG V2")
    parser.add_argument("command", choices=["init", "publish", "list", "search", "install", "info", "remove", "stale"])
    parser.add_argument("arg", nargs="?", help="Tool path (publish), tool name (install/info/remove), or query (search)")
    parser.add_argument("--name", default="Team Windsurf Tools", help="Registry name (init)")
    parser.add_argument("--registry", default=DEFAULT_REGISTRY_DIR, help="Registry directory")
    parser.add_argument("--tags", default="", help="Comma-separated tags (publish)")
    parser.add_argument("--target", default=None, help="Install target directory")
    parser.add_argument("--json", action="store_true", help="JSON output")
    args = parser.parse_args()

    if args.command == "init":
        init_registry(args.registry, args.name)
    elif args.command == "publish":
        if not args.arg:
            print("Error: Provide path to tool kit", file=sys.stderr)
            sys.exit(1)
        tags = [t.strip() for t in args.tags.split(",") if t.strip()]
        publish_tool(args.registry, args.arg, tags)
    elif args.command == "list":
        list_tools(args.registry, json_output=args.json)
    elif args.command == "search":
        if not args.arg:
            print("Error: Provide search query", file=sys.stderr)
            sys.exit(1)
        search_tools(args.registry, args.arg, json_output=args.json)
    elif args.command == "install":
        if not args.arg:
            print("Error: Provide tool name", file=sys.stderr)
            sys.exit(1)
        install_tool(args.registry, args.arg, args.target)
    elif args.command == "info":
        if not args.arg:
            print("Error: Provide tool name", file=sys.stderr)
            sys.exit(1)
        tool_info(args.registry, args.arg)
    elif args.command == "remove":
        if not args.arg:
            print("Error: Provide tool name", file=sys.stderr)
            sys.exit(1)
        remove_tool(args.registry, args.arg)
    elif args.command == "stale":
        check_stale(args.registry, json_output=args.json)


if __name__ == "__main__":
    main()
